import { defineConfig } from 'vitepress'

export default defineConfig({
  lang: 'zh-CN',
  title: 'Langfuse 中文指南',
  description: 'Langfuse 非官方中文学习站（社区原型）',
  base: process.env.DOCS_BASE || '/',
  cleanUrls: true,
  themeConfig: {
    logo: '🪢',
    nav: [
      { text: '首页', link: '/' },
      { text: '入门指南', link: '/guide/overview' },
      { text: '官方文档翻译', link: '/official/observability/overview' },
      { text: '英文原文 ↗', link: 'https://langfuse.com/docs' }
    ],
    sidebar: [
      { text: '开始使用', items: [
        { text: '什么是 Langfuse', link: '/guide/overview' },
        { text: 'Python 快速接入', link: '/guide/python-quickstart' }
      ]},
      { text: '核心功能', items: [
        { text: '可观测性与追踪', link: '/features/observability' },
        { text: '提示词管理', link: '/features/prompts' },
        { text: '评估与数据集', link: '/features/evaluations' },
        { text: 'LLM Playground', link: '/features/playground' }
      ]},
      { text: '官方文档中文翻译', items: [
        { text: '可观测性与追踪', link: '/official/observability/overview' },
        { text: 'Observation 类型', link: '/official/observability/features/observation-types' },
        { text: '日志级别', link: '/official/observability/features/log-levels' },
        { text: 'Session 会话', link: '/official/observability/features/sessions' },
        { text: '用户追踪', link: '/official/observability/features/users' },
        { text: '标签', link: '/official/observability/features/tags' },
        { text: '追踪核心概念', link: '/official/observability/data-model' },
        { text: '环境配置', link: '/official/observability/features/environments' },
        { text: '元数据', link: '/official/observability/features/metadata' },
        { text: '疑难解答与 FAQ', link: '/official/observability/troubleshooting-and-faq' },
        { text: 'MCP 追踪', link: '/official/observability/features/mcp-tracing' },
        { text: 'Agent 图', link: '/official/observability/features/agent-graphs' },
        { text: '评论', link: '/official/observability/features/comments' },
        { text: '输出纠正', link: '/official/observability/features/corrections' },
        { text: 'SDK 疑难解答', link: '/official/observability/sdk/troubleshooting-and-faq' },
        { text: '全文搜索', link: '/official/observability/features/full-text-search' },
        { text: '筛选搜索栏', link: '/official/observability/features/filter-search-bar' },
        { text: '采样', link: '/official/observability/features/sampling' },
        { text: 'Pulse 异常分析', link: '/official/observability/features/pulse' },
        { text: '事件表格与图表', link: '/official/observability/features/events-table-charts' },
        { text: '用户反馈', link: '/official/observability/features/user-feedback' },
        { text: 'Trace ID 与分布式追踪', link: '/official/observability/features/trace-ids-and-distributed-tracing' },
        { text: '事件队列与批量发送', link: '/official/observability/features/queuing-batching' },
        { text: 'Trace 链接', link: '/official/observability/features/url' },
        { text: 'Web Callouts', link: '/official/observability/features/web-callouts' },
        { text: 'Agent 访问可观测性', link: '/official/observability/features/agentic-access' },
        { text: 'SDK 升级路径', link: '/official/observability/sdk/upgrade-path/index' },
        { text: 'JS/TS v3 升级 v4', link: '/official/observability/sdk/upgrade-path/js-v3-to-v4' },
        { text: 'Langfuse v4', link: '/official/v4' },
        { text: '产品路线图', link: '/official/roadmap' },
        { text: 'Langfuse Assistant', link: '/official/langfuse-assistant' },
        { text: '提示词缓存', link: '/official/prompt-management/features/caching' },
        { text: '提示词版本控制', link: '/official/prompt-management/features/prompt-version-control' },
        { text: '提示词 Config', link: '/official/prompt-management/features/config' },
        { text: '发布版本与组件版本', link: '/official/observability/features/releases-and-versioning' },
        { text: 'Score 概览', link: '/official/evaluation/scores/overview' },
        { text: 'Score 数据模型', link: '/official/evaluation/scores/data-model' },
        { text: '生产流量在线评估', link: '/official/evaluation/get-started/online' },
        { text: '通过 SDK 查询数据', link: '/official/api-and-data-platform/features/query-via-sdk' },
        { text: '提示词文件夹', link: '/official/prompt-management/features/folders' },
        { text: '提示词变量', link: '/official/prompt-management/features/variables' },
        { text: '消息占位符', link: '/official/prompt-management/features/message-placeholders' },
        { text: '高可用与回退提示词', link: '/official/prompt-management/features/guaranteed-availability' },
        { text: '提示词组合', link: '/official/prompt-management/features/composability' },
        { text: '提示词 A/B 测试', link: '/official/prompt-management/features/a-b-testing' },
        { text: 'Webhook 与 Slack 集成', link: '/official/prompt-management/features/webhooks-slack-integrations' },
        { text: 'LLM Playground', link: '/official/prompt-management/features/playground' },
        { text: '提示词与 Trace 关联', link: '/official/prompt-management/features/link-to-traces' },
        { text: 'Agent 提示词管理', link: '/official/prompt-management/features/agentic-access' },
        { text: 'n8n 节点', link: '/official/prompt-management/features/n8n-node' },
        { text: 'Agent 评估', link: '/official/evaluation/agentic-access' },
        { text: 'OpenTelemetry 实验', link: '/official/evaluation/experiments/experiments-via-opentelemetry' },
        { text: 'UI 手动评分', link: '/official/evaluation/evaluation-methods/scores-via-ui' },
        { text: '标注队列', link: '/official/evaluation/evaluation-methods/annotation-queues' },
        { text: '比较实验', link: '/official/evaluation/experiments/compare-experiments' },
        { text: '指标与分析', link: '/official/metrics/overview' },
        { text: 'Metrics API', link: '/official/metrics/features/metrics-api' },
        { text: '从 UI 导出数据', link: '/official/api-and-data-platform/features/export-from-ui' },
        { text: '支出提醒', link: '/official/administration/spend-alerts' },
        { text: '计费单位', link: '/official/administration/billable-units' },
        { text: '数据保留策略', link: '/official/administration/data-retention' },
        { text: '审计日志', link: '/official/administration/audit-logs' },
        { text: '管理 FAQ', link: '/official/administration/troubleshooting-and-faq' },
        { text: '评估 FAQ', link: '/official/evaluation/troubleshooting-and-faq' },
        { text: '提示词 FAQ', link: '/official/prompt-management/troubleshooting-and-faq' },
        { text: '文档 MCP 服务器', link: '/official/docs-mcp' },
        { text: 'Ask AI', link: '/official/ask-ai' },
        { text: '提示词管理', link: '/official/prompt-management/overview' },
        { text: '提示词快速开始（部分）', link: '/official/prompt-management/get-started' },
        { text: '提示词数据模型（部分）', link: '/official/prompt-management/data-model' },
        { text: 'API 与数据平台', link: '/official/api-and-data-platform/overview' },
        { text: 'Langfuse CLI', link: '/official/api-and-data-platform/features/cli' },
        { text: 'Agent Skill', link: '/official/api-and-data-platform/features/agent-skill' },
        { text: 'LLM 应用评估', link: '/official/evaluation/overview' }
      ]},
      { text: '关于', items: [ { text: '翻译说明与许可', link: '/about' } ] }
    ],
    outline: { label: '本页目录', level: [2, 3] },
    docFooter: { prev: '上一篇', next: '下一篇' },
    lastUpdated: { text: '更新时间' },
    search: { provider: 'local', options: { translations: { button: { buttonText: '搜索文档', buttonAriaLabel: '搜索文档' }, modal: { noResultsText: '没有找到结果', resetButtonTitle: '清空查询', footer: { selectText: '选择', navigateText: '切换' } } } } },
    socialLinks: [{ icon: 'github', link: 'https://github.com/langfuse/langfuse-docs' }],
    footer: { message: '非官方社区中文学习原型；内容以 Langfuse 官方文档为准。', copyright: 'Langfuse 是其权利人的商标。' }
  }
})
